### ISSUE TITLE
Optimize `include_tools` and `system_prompt` config option

### ISSUE THREAD

**Issue by OskarStark** [php-llm/llm-chain-bundle#72]
Follows
* #68 

Not a fan of having it on the same level like `system_prompt`, maybe we should be allowed to use sth like:

```yaml
foo:
    system_prompt: 'My prompt'
```

and

```yaml
foo:
    system_prompt:
        prompt: 'My prompt'
        include_tool_definitions: true
```
