### ISSUE TITLE
Cannot serialize Symfony\Component\HttpClient\Response\AsyncResponse

### ISSUE THREAD

**Issue by d0niek** [php-llm/llm-chain-bundle#90]
Hello again!

I want to configure OpenRouter by my own and here is my config file:

```yaml
# config/packages/llm_chain.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    llm_chain.chain.long_description_generator:
        class: PhpLlm\LlmChain\Chain
        arguments:
            $platform: '@llm_chain.platform.openrouter'
            $llm: '@llm_chain.chain.long_description_generator.llm'
            $inputProcessors:
                - '@PhpLlm\LlmChain\Chain\InputProcessor\LlmOverrideInputProcessor'
            $outputProcessors:
                - '@App\Ai\Infrastructure\PhpLlm\OutputProcessor\AiMetadata'
            $logger: '@Psr\Log\LoggerInterface'

    llm_chain.chain.long_description_generator.llm:
        class: PhpLlm\LlmChain\Bridge\OpenRouter\GenericModel
        arguments:
            $name: '%env(string:OPENROUTER_MODEL)%'
        tags:
            - { name: 'llm_chain.model.language_model' }

    llm_chain.platform.openrouter:
        class: PhpLlm\LlmChain\Platform
        factory: ['PhpLlm\LlmChain\Bridge\OpenRouter\PlatformFactory', 'create']
        arguments:
            $apiKey: '%env(string:OPENROUTER_API_KEY)%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
        tags:
            - { name: 'llm_chain.platform' }

    PhpLlm\LlmChain\Chain\InputProcessor\LlmOverrideInputProcessor: ~

    PhpLlm\LlmChain\Chain\Toolbox\Tool\Clock: ~

llm_chain:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'

    chain:
        default:
            platform: 'llm_chain.platform.openai'
            model:
                name: 'GPT'
                version: 'gpt-4o-mini'
            system_prompt: |
                You are a helpful assistant and you can provide the current date and time.
            tools:
                - 'PhpLlm\LlmChain\Chain\Toolbox\Tool\Clock'

when@dev:
    services:
        llm_chain.traceable_platform.openrouter:
            class: PhpLlm\LlmChainBundle\Profiler\TraceablePlatform
            decorates: 'llm_chain.platform.openrouter'
            arguments: ['@.inner']
            tags:
                - { name: 'llm_chain.traceable_platform' }
```

It works (!) but after finished my request, Symfony throws an error mentioned in title.

For me a problem is with `when@dev` section but I don't know how to fix it. Do you have any suggestions or idea?

**Comment by d0niek** [comment]
So `OpenRouter::ResponseConverter` doesn't "resolves" a response correctly?

**Comment by chr-hertel** [comment]
It's just that the call to the ResponseConverter is delay to enable concurrency, see
* https://github.com/php-llm/llm-chain/blob/main/src/Platform/Platform.php#L75-L79
* https://github.com/php-llm/llm-chain/blob/main/src/Platform/Response/AsyncResponse.php#L48-L62

**Comment by d0niek** [comment]
Sorry but I don't understand where's the problem :-/

Exactly the same error I've got with yours default config:

```yaml
# config/packages/llm_chain.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    PhpLlm\LlmChain\Chain\Toolbox\Tool\Clock: null

llm_chain:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'

    chain:
        default:
            platform: 'llm_chain.platform.openai'
            model:
                name: 'GPT'
                version: 'gpt-4o-mini'
            system_prompt: |
                You are a helpful assistant and you can provide the current date and time.
            tools:
                - 'PhpLlm\LlmChain\Chain\Toolbox\Tool\Clock'
```

and with this simple code:

```php
<?php

declare(strict_types=1);

namespace App\Ai\Infrastructure\ApiPlatform\State\Processor;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Ai\Domain\Model\SpeechToText;
use PhpLlm\LlmChain\Bridge\OpenAI\Whisper;
use PhpLlm\LlmChain\Model\Message\Content\Audio;
use PhpLlm\LlmChain\PlatformInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Vich\UploaderBundle\Storage\StorageInterface;

/**
 * @implements ProcessorInterface<SpeechToText, SpeechToText>
 */
final readonly class SpeechToTextPost implements ProcessorInterface
{
    public function __construct(
        #[Autowire(service: 'llm_chain.platform.openai')]
        private readonly PlatformInterface $platform,
        private readonly StorageInterface $storage,
        private readonly string $projectDir,
    ) {}

    #[\Override]
    public function process(
        mixed $data,
        Operation $operation,
        array $uriVariables = [],
        array $context = [],
    ): SpeechToText {
        $path = $this->storage->resolvePath($data->audio, 'file');
        $audio = Audio::fromFile("{$this->projectDir}/public/media/{$path}");
        $model = new Whisper();
        $data->text = $this->platform->request($model, $audio)->getContent();

        return $data;
    }
}
```

The code works only when I pass `llm_chain.traceable_platform.openai.inner` instead of `llm_chain.platform.openai`.

I'm using php `v8.3.20`. Here is my **composer.json**:

```bash
api-platform/doctrine-orm           4.1.12  Doctrine ORM bridge
api-platform/schema-generator       5.2.4   Various tools to generate a dat...
api-platform/symfony                4.1.12  Symfony API Platform integration
doctrine/annotations                2.0.2   Docblock Annotations Parser
doctrine/doctrine-bundle            2.14.0  Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle 3.4.2   Symfony DoctrineMigrationsBundle
doctrine/orm                        3.3.3   Object-Relational-Mapper for PHP
dragonmantank/cron-expression       3.4.0   CRON for PHP: Calculate the nex...
erusev/parsedown                    1.7.4   Parser for Markdown.
gesdinet/jwt-refresh-token-bundle   1.4.0   Implements a refresh token syst...
hautelook/alice-bundle              2.15.1  Symfony bundle to manage fixtur...
league/flysystem-bundle             3.4.0   Symfony bundle integrating Flys...
lexik/jwt-authentication-bundle     3.1.1   This bundle provides JWT authen...
nelmio/cors-bundle                  2.5.0   Adds CORS (Cross-Origin Resourc...
php-llm/llm-chain-bundle            0.21    Symfony integration bundle for ...
phpmd/phpmd                         2.15.0  PHPMD is a spin-off project of ...
phpstan/phpdoc-parser               2.1.0   PHPDoc parser with support for ...
phpunit/phpunit                     10.5.46 The PHP Unit Testing framework.
rector/rector                       2.0.16  Instant Upgrade and Automated R...
runtime/frankenphp-symfony          0.2.0   FrankenPHP runtime for Symfony
sentry/sentry-symfony               5.2.0   Symfony integration for Sentry ...
stof/doctrine-extensions-bundle     1.14.0  Integration of the gedmo/doctri...
symfony/asset                       6.4.13  Manages URL generation and vers...
symfony/browser-kit                 6.4.19  Simulates the behavior of a web...
symfony/console                     6.4.21  Eases the creation of beautiful...
symfony/css-selector                6.4.13  Converts CSS selectors to XPath...
symfony/debug-bundle                6.4.13  Provides a tight integration of...
symfony/doctrine-messenger          6.4.18  Symfony Doctrine Messenger Bridge
symfony/dotenv                      6.4.16  Registers environment variables...
symfony/expression-language         6.4.13  Provides an engine that can com...
symfony/flex                        2.7.0   Composer plugin for Symfony
symfony/form                        6.4.21  Allows to easily create, proces...
symfony/framework-bundle            6.4.21  Provides a tight integration be...
symfony/intl                        6.4.21  Provides access to the localiza...
symfony/mailer                      6.4.21  Helps sending emails
symfony/maker-bundle                1.63.0  Symfony Maker helps you create ...
symfony/mercure-bundle              0.3.9   Symfony MercureBundle
symfony/messenger                   6.4.21  Helps applications send and rec...
symfony/monolog-bundle              3.10.0  Symfony MonologBundle
symfony/notifier                    6.4.21  Sends notifications via one or ...
symfony/phpunit-bridge              6.4.16  Provides utilities for PHPUnit,...
symfony/property-access             6.4.18  Provides functions to read and ...
symfony/property-info               6.4.18  Extracts information about PHP ...
symfony/runtime                     6.4.14  Enables decoupling PHP applicat...
symfony/scheduler                   6.4.18  Provides scheduling through Sym...
symfony/security-bundle             6.4.21  Provides a tight integration of...
symfony/serializer                  6.4.21  Handles serializing and deseria...
symfony/stopwatch                   6.4.19  Provides a way to profile code
symfony/translation                 6.4.21  Provides tools to international...
symfony/twig-bundle                 6.4.13  Provides a tight integration of...
symfony/validator                   6.4.21  Provides tools to validate values
symfony/var-dumper                  6.4.21  Provides mechanisms for walking...
symfony/web-profiler-bundle         6.4.19  Provides a development tool tha...
symfony/yaml                        6.4.21  Loads and dumps YAML files
symfonycasts/reset-password-bundle  1.23.1  Symfony bundle that adds passwo...
symfonycasts/verify-email-bundle    1.17.3  Simple, stylish Email Verificat...
symplify/easy-coding-standard       12.5.18 Use Coding Standard with 0-know...
twig/cssinliner-extra               3.21.0  A Twig extension to allow inlin...
twig/extra-bundle                   3.21.0  A Symfony bundle for extra Twig...
twig/inky-extra                     3.21.0  A Twig extension for the inky e...
twig/intl-extra                     3.21.0  A Twig extension for Intl
vich/uploader-bundle                2.6.1   Ease file uploads attached to e...
vimeo/psalm                         6.11.0  A static analysis tool for find...
```
